# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PoN8H1Owj3Lg-mYUq8nTcHxx1rYt2yKR
"""

import pandas as pd
import numpy as np
info = np.array(['p','a','n','d','a','s'])
a = pd.Series(info)
print(a)

import pandas as pd
# a list of strings
x = ['Python','Pandas']
# Calling DataFrame constructor on list
df = pd.DataFrame(x)
print(df)

import pandas as pd
import numpy as np
a=pd.Series(['java','c','c++',np.nan])
a.map({'java':'core'})

import pandas as pd
import numpy as np
a=pd.Series(['java','c','c++',np.nan])
a.map({'java':'core'})
a.map('i like {}'.format,na_action='ignore')

s=pd.Series(["a","b","c"],
name="vais")
s.to_frame()

import pandas as pd
import matplotlib.pyplot as plt
emp=['Amit','Piyush','Ankit','Dharamveer']
id=[102,107,109,112]
emp_series=pd.Series(emp)
id_series=pd.Series(id)
frame={'Emp':emp_series,'ID':id_series}
result=pd.DataFrame(frame)
print(result)

